### ISSUE TITLE
Workers

### ISSUE THREAD

**Issue by adespawn** [Stowarzyszenie-Talent/st-make#12]
https://github.com/Stowarzyszenie-Talent/st-make/blob/f6fd499a9d9c2838ac604879e600b3a5c226fbe2/.github/workflows/Ubuntu.yaml#L3

W sytuacji gdy mamy włączone workflows na każdy push, to chyba nie ma sensu dawać zadań także na PR, bo to powoduje podwójne zlecenie zadań, w skutek czego znaczące wydłużenie już i tak długiego czasu potrzebengo na uruchomienie testów

**Comment by A-dead-pixel** [comment]
A może by ograniczyć workflowy na `push`ach tylko do main brancha?
No chyba, że korzystacie z obecnego stanu.

**Comment by adespawn** [comment]
Jest to doś przydatne jak np. zapomnę uruchomić testów u siebie, i widzę że coś nie działa.

**Comment by A-dead-pixel** [comment]
No ok, może później to zmienimy.

**Comment by A-dead-pixel** [comment]
Zrobione w [80cb2c7](https://github.com/Stowarzyszenie-Talent/st-make/commit/80cb2c760960b977f9f586a7f04d011ba7c46070).
