### ISSUE TITLE
Github runners

### ISSUE THREAD

**Issue by adespawn** [Stowarzyszenie-Talent/st-make#2]
Job [GithubRunner.yaml](https://github.com/Stowarzyszenie-Talent/st-make/blob/main/.github/workflows/GithubRunner.yaml) runs only 3 tests out of over 200. [3 passed, 251 skipped in 2.67s](https://github.com/Stowarzyszenie-Talent/st-make/actions/runs/7929136573/job/21648775737)
Potentially try to fix this, to run more tests.

Job [macOS.yaml](https://github.com/Stowarzyszenie-Talent/st-make/blob/main/.github/workflows/macOS.yaml)  [takes around 20 minutes to run](https://github.com/Stowarzyszenie-Talent/st-make/actions/runs/7929136574/usage)
Check if this will be a problem when it comes to limited amount of free actions minutes.

**Comment by A-dead-pixel** [comment]
Almost all tests being skipped on that runner seems to be an upstream issue (it could even be intended), see https://github.com/sio2project/sinol-make/actions/runs/7898991172/job/21557496226.

**Comment by adespawn** [comment]
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions : It looks like billable minutes apply only to private repos, so it won't count to the action minutes limit
